### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by rpCal**
Hi,
I saw you repo in green ruby new ( link: http://greenruby.org/grn-133.html ). I look on source and I want to help you with this library. 
I have few hours and first I want to know this library better so I start add docs. I try to use idiomatic.js as code style and I dont change any line of your code. (I only add comments)
I have hope that this will help you to get this lib better.

ps. if you want to remove .gitignore file. I add it only becouse of webstorm
cheers.

### CODE REVIEW

**Comment by dfcreative** [comment]
Hi! Wonderful, thanks a lot!

**Comment by rpCal** [comment]
Thanks for merge :) I thought that there will be some issue with this. 
Can you help me to understand two functions that I dont finish yet? function _initLayoutParams and _placeItem this is core of library but Im not sure how should I read this. Could you explain a little bit how this two functions work?

**Comment by dfcreative** [comment]
Actually yes, there is an issue with indentation. Now code has mixed tab/spaces indentation, which looks ugly in github editor :(
`_initLayoutParams` just initializes the variables needed for _update, `_placeItem` just sets the proper position for an item, like so, I don't remember exact details, it's old code.
Better take a look at the [cascade](https://github.com/kudago/cascade)

**Comment by rpCal** [comment]
Yea, I notice this too, so I will make it better. I will update this in next pull request.
O nice! I dont know that there is successor. I will look at this code too. Thanks

**Pull request merged**
